spring:
  application:
    index: 1
    name: Boot
  mvc:
    favicon:
      enabled: true
    view:
      suffix: .jsp

server:
  port: 82
  contextPath: /oos
  error:
    path: /error
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
  session:
    timeout: 60
logging:
  file: logs\oos_log.log
  level: info
oos:
  local-resource-path: D:\resource
  swagger-enable: true
  #oos-url: http://oos.it-teaching.com
  #oos-url: https://docview.mingdao.com
  #oos-url: http://office.scaqjg.com